---

- name: Remove IAPP Configs
  ansible.builtin.include_tasks: remove-horizon-iapp.yml
  with_items:
    - ltm
    - apm
    - uag
    - no_ws1
    - ws1_single
  loop_control:
    loop_var: iapp_templ
