---

- name: Remove IAPP Configs
  ansible.builtin.include_tasks: remove-horizon-iapp.yml
  with_items:
    - f5.horizon.ltm
    - f5.horizon.apm
    - f5.horizon.uag
    - f5.horizon.no_ws1
    - f5.horizon.ws1_single
    - iapp.oauth.jwt.provider
  loop_control:
    loop_var: iapp_templ
