---
- name: Check for vars, for configuration "{{ iapp_templ }}"
  ansible.builtin.stat:
    path: "/git/vars/horizon_iapp_{{ iapp_templ }}.yml"
  register: variables_bypass

- name: Include vars for configuration "{{ iapp_templ }}"
  ansible.builtin.include_vars:
    file: "/git/vars/horizon_iapp_{{ iapp_templ }}.yml"
  when: variables_bypass.stat.exists

- name: Build JSON payload for configuration "{{ iapp_templ }}"
  ansible.builtin.template: src=f5.horizon.{{ iapp_templ | lower }}.j2 dest=/tmp/f5.horizon.json

- name: Deploy F5 Horizon iApp for configuration "{{ iapp_templ }}"
  f5networks.f5_modules.bigip_iapp_service: # Using Collections if not use - bigip_iapp_service:
    name: "VMware-Horizon-{{ iapp_templ }}"
    template: "{{ iapp_template_name }}"
    parameters: "{{ lookup('template', '/tmp/f5.horizon.json') }}"
    provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: false
  delegate_to: localhost
