---
- name: Check for vars, for configuration "{{ iapp_templ }}"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/vars/{{ iapp_templ }}.yml"
  register: variables_bypass

- name: Include vars for configuration "{{ iapp_templ }}"
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/vars/{{ iapp_templ }}.yml"
  when: variables_bypass.stat.exists

- name: Build JSON payload for configuration "{{ iapp_templ }}"
  ansible.builtin.template: src={{ iapp_templ | lower }}.j2 dest=/tmp/f5.horizon.json

- name: Authenticate to BIG-IP and retrieve token
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/mgmt/shared/authn/login"
    method: POST
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    force_basic_auth: true
    validate_certs: false
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      username: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      loginProviderName: "tmos"
    return_content: true
  register: bigip_auth_response
  no_log: true

- name: Set token fact
  ansible.builtin.set_fact:
    iapp_bigip_mgmt_token: "{{ bigip_auth_response.json.token.token }}"

- name: Deploy F5 Horizon iApp for configuration "{{ iapp_templ }}"
  f5networks.f5_modules.bigip_iapp_service: # Using Collections if not use - bigip_iapp_service:
    name: "Omnissa-{{ iapp_templ }}"
    template: "{{ iapp_template_name }}"
    parameters: "{{ lookup('template', '/tmp/f5.horizon.json') }}"
    provider:
      server: "{{ ansible_host }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: false
  delegate_to: localhost
